# Generated by Django 4.2.27 on 2026-01-09 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Обязательное поле. Не менее 1 символа.', max_length=200, verbose_name='Название')),
                ('author', models.CharField(help_text='Обязательное поле. Минимум 2 символа.', max_length=150, verbose_name='Автор')),
                ('year', models.PositiveIntegerField(help_text='Должен быть от 1 до текущего года.', verbose_name='Год издания')),
                ('genre', models.CharField(help_text='Обязательное поле. Минимум 2 символа.', max_length=100, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('status', models.CharField(choices=[('not_started', 'Не начата'), ('reading', 'Читаю'), ('read', 'Прочитана')], default='not_started', max_length=20, verbose_name='Статус чтения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
    ]
